```
@startuml
!theme plain
title BPMN AS-IS: Оформление заказа (до проекта)

|#LightBlue|Клиент|
start
:Добавить товар в корзину;
:Открыть корзину;
:Нажать "Оформить заказ";

|#LightYellow|Frontend|
:Отправить запрос в монолит;

|#LightPink|Монолит|
:Проверить остатки в ERP;

if (Товар в наличии?) then (нет)
  |#LightBlue|Клиент|
  :Получить отказ;
  stop
else (да)
endif

:Рассчитать доставку (фикс. тариф);
:Создать заказ в ERP;

|#LightGreen|Payment Gateway|
:Оплата;

if (Оплата прошла?) then (нет)
  |#LightPink|Монолит|
  :Заказ висит в статусе PENDING;
  note right: Нет автоснятия\nрезерва
  stop
else (да)
endif

|#Orange|Оператор|
:Вручную сплитовать заказ;
:Вручную передать заказ\nв курьерскую службу;

|#LightGray|Notification|
:Отправить уведомление;
stop

@enduml
```
